baseurl = "https://www.whatsajunting.com/"
title = "whatsajunting"

googleAnalytics = "UA-56349103-1"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "whatsajunting"

[params]
    author = "Junting Lu"
    description = "Junting's personal website"
    keywords = "blog,developer,personal"
    info = "Software Engineer | Aspiring Emojineer"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/gnitnuj/"
[[params.social]]
    name = "Email"
    weight = 2
    url = "mailto:junting.lu@gmail.com"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/junting/"

[[menu.main]]
    name = "Random"
    weight = 1
    url  = "/random/"
[[menu.main]]
    name = "Code"
    weight = 1
    url  = "/code/"
[[menu.main]]
    name = "Words"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
