baseurl = "https://www.whatsajunting.com/"
title = "whatsajunting"

googleAnalytics = "UA-56349103-1"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Junting Lu"
    description = "Junting's personal website"
    keywords = "blog,developer,personal"
    info = "Aspiring Emojineer | Engineering Manager"
    avatarurl = "images/avatar.jpg"

    hideCredits = true
    hideCopyright = true

    rtl = false

    math = false
	custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/gnitnuj/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/junting/"

[[menu.main]]
    name = "Misc."
    weight = 1
    url  = "/misc/"
[[menu.main]]
    name = "Code"
    weight = 2
    url  = "/code/"
[[menu.main]]
    name = "Words"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 4
    url = "/about/"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"